name = "card-optimizer"
compatibility_date = "2024-01-15"
pages_build_output_dir = "dist"

# Production
[env.production]

[[env.production.d1_databases]]
binding = "DB"
database_name = "card-optimizer-db"
database_id = "86f6b550-adcb-4955-a48a-a103998971af"
migrations_dir = "database/migrations"

[env.production.vars]
ENVIRONMENT = "production"

# Staging / Preview
[env.preview]

[[env.preview.d1_databases]]
binding = "DB"
database_name = "card-optimizer-db-staging"
database_id = "bf05e6d6-cef0-4b0c-bb69-9a81ff641264"
migrations_dir = "database/migrations"

[env.preview.vars]
ENVIRONMENT = "staging"

# Local development
[[d1_databases]]
binding = "DB"
database_name = "card-optimizer-db"
database_id = "86f6b550-adcb-4955-a48a-a103998971af"
migrations_dir = "database/migrations"

[vars]
ENVIRONMENT = "local"
